import type { PlanGraph, Wall } from "@/lib/kernel/types";

/**
 * Export a plan graph as an IFC4 STEP-21 file (ISO 16739-1).
 *
 * This is a minimal, hand-rolled STEP-21 writer. It emits a structurally
 * valid spatial hierarchy — IfcProject → IfcSite → IfcBuilding →
 * IfcBuildingStorey — together with IfcWall entities for each wall and a
 * single IfcSlab for the storey floor. Geometry is carried as swept-solid
 * representations referenced through the standard IFC representation chain.
 *
 * DECISION: spec §3.3 also lists IfcDoor / IfcWindow / IfcSpace. Per the
 * CORE scope this writer is limited to IfcWall + IfcSlab plus the spatial
 * containers; openings and spaces are left as TODO(v2) below.
 *
 * See docs/v2-spec.md §3.3.
 */
export function exportIFC4(graph: PlanGraph): string {
  // --- STEP entity instance allocator ------------------------------------
  const lines: string[] = [];
  let nextId = 1;
  /** Append an entity, return its `#id` reference. */
  const add = (body: string): string => {
    const id = nextId++;
    lines.push(`#${id}= ${body};`);
    return `#${id}`;
  };

  const guid = pseudoGuid;

  // --- Units --------------------------------------------------------------
  // The kernel works in millimeters; declare SI length in millimetres.
  const lengthUnit = add(
    "IFCSIUNIT(*,.LENGTHUNIT.,.MILLI.,.METRE.)",
  );
  const areaUnit = add("IFCSIUNIT(*,.AREAUNIT.,$,.SQUARE_METRE.)");
  const volumeUnit = add("IFCSIUNIT(*,.VOLUMEUNIT.,$,.CUBIC_METRE.)");
  const angleUnit = add("IFCSIUNIT(*,.PLANEANGLEUNIT.,$,.RADIAN.)");
  const unitAssignment = add(
    `IFCUNITASSIGNMENT((${lengthUnit},${areaUnit},${volumeUnit},${angleUnit}))`,
  );

  // --- Geometric context --------------------------------------------------
  const origin = add("IFCCARTESIANPOINT((0.,0.,0.))");
  const axisZ = add("IFCDIRECTION((0.,0.,1.))");
  const axisX = add("IFCDIRECTION((1.,0.,0.))");
  const worldPlacement = add(
    `IFCAXIS2PLACEMENT3D(${origin},${axisZ},${axisX})`,
  );
  const trueNorth = add("IFCDIRECTION((0.,1.))");
  const geomContext = add(
    `IFCGEOMETRICREPRESENTATIONCONTEXT($,'Model',3,1.0E-5,${worldPlacement},${trueNorth})`,
  );

  // --- Project / spatial hierarchy ---------------------------------------
  const project = add(
    `IFCPROJECT('${guid()}',$,'Atelier Project','Generated by Atelier v2',$,$,$,(${geomContext}),${unitAssignment})`,
  );

  const sitePlacement = add(`IFCLOCALPLACEMENT($,${worldPlacement})`);
  const site = add(
    `IFCSITE('${guid()}',$,'Site',$,$,${sitePlacement},$,$,.ELEMENT.,$,$,$,$,$)`,
  );

  const buildingPlacement = add(
    `IFCLOCALPLACEMENT(${sitePlacement},${worldPlacement})`,
  );
  const building = add(
    `IFCBUILDING('${guid()}',$,'Building',$,$,${buildingPlacement},$,$,.ELEMENT.,$,$,$)`,
  );

  const storeyPlacement = add(
    `IFCLOCALPLACEMENT(${buildingPlacement},${worldPlacement})`,
  );
  const storey = add(
    `IFCBUILDINGSTOREY('${guid()}',$,'${escapeStep(graph.level)}',$,$,${storeyPlacement},$,$,.ELEMENT.,0.)`,
  );

  // Aggregation relationships linking the spatial hierarchy.
  add(
    `IFCRELAGGREGATES('${guid()}',$,$,$,${project},(${site}))`,
  );
  add(
    `IFCRELAGGREGATES('${guid()}',$,$,$,${site},(${building}))`,
  );
  add(
    `IFCRELAGGREGATES('${guid()}',$,$,$,${building},(${storey}))`,
  );

  // --- Walls --------------------------------------------------------------
  const wallRefs: string[] = [];
  for (const wall of graph.walls) {
    wallRefs.push(emitWall(wall, storeyPlacement, geomContext, guid, add));
  }

  // --- Slab (storey floor) ------------------------------------------------
  const slabRef = emitSlab(graph, storeyPlacement, geomContext, guid, add);

  // Spatial containment: every physical element belongs to the storey.
  const contained = [...wallRefs, slabRef];
  if (contained.length > 0) {
    add(
      `IFCRELCONTAINEDINSPATIALSTRUCTURE('${guid()}',$,$,$,(${contained.join(",")}),${storey})`,
    );
  }

  // TODO(v2): emit IfcDoor / IfcWindow with IfcOpeningElement voids cut into
  // the host walls, and IfcSpace entities for each room polygon.

  return assembleStepFile(lines);
}

/** Emit one IfcWall with an extruded swept-solid body. Returns its ref. */
function emitWall(
  wall: Wall,
  storeyPlacement: string,
  geomContext: string,
  guid: () => string,
  add: (body: string) => string,
): string {
  const len = Math.hypot(wall.end.x - wall.start.x, wall.end.y - wall.start.y);
  // DECISION: the kernel carries no per-wall height; use a conventional
  // 2700 mm storey height for the extrusion depth.
  const heightMm = 2700;

  // Local placement at the wall start, rotated so +X runs along the wall.
  const dirX = len > 0 ? (wall.end.x - wall.start.x) / len : 1;
  const dirY = len > 0 ? (wall.end.y - wall.start.y) / len : 0;
  const startPt = add(
    `IFCCARTESIANPOINT((${num(wall.start.x)},${num(wall.start.y)},0.))`,
  );
  const wallAxisZ = add("IFCDIRECTION((0.,0.,1.))");
  const wallAxisX = add(`IFCDIRECTION((${num(dirX)},${num(dirY)},0.))`);
  const wallPlacement3d = add(
    `IFCAXIS2PLACEMENT3D(${startPt},${wallAxisZ},${wallAxisX})`,
  );
  const wallPlacement = add(
    `IFCLOCALPLACEMENT(${storeyPlacement},${wallPlacement3d})`,
  );

  // Rectangular profile: wall length × thickness, swept upward.
  const profileOrigin = add(
    `IFCCARTESIANPOINT((${num(len / 2)},0.))`,
  );
  const profileAxisX = add("IFCDIRECTION((1.,0.))");
  const profilePlacement = add(
    `IFCAXIS2PLACEMENT2D(${profileOrigin},${profileAxisX})`,
  );
  const profile = add(
    `IFCRECTANGLEPROFILEDEF(.AREA.,$,${profilePlacement},${num(len)},${num(wall.thicknessMm)})`,
  );

  const extrudeOrigin = add("IFCCARTESIANPOINT((0.,0.,0.))");
  const extrudeAxisZ = add("IFCDIRECTION((0.,0.,1.))");
  const extrudeAxisX = add("IFCDIRECTION((1.,0.,0.))");
  const extrudePlacement = add(
    `IFCAXIS2PLACEMENT3D(${extrudeOrigin},${extrudeAxisZ},${extrudeAxisX})`,
  );
  const extrudeDir = add("IFCDIRECTION((0.,0.,1.))");
  const solid = add(
    `IFCEXTRUDEDAREASOLID(${profile},${extrudePlacement},${extrudeDir},${num(heightMm)})`,
  );
  const shapeRep = add(
    `IFCSHAPEREPRESENTATION(${geomContext},'Body','SweptSolid',(${solid}))`,
  );
  const productShape = add(
    `IFCPRODUCTDEFINITIONSHAPE($,$,(${shapeRep}))`,
  );

  const predefined = wall.kind === "exterior" ? ".SOLIDWALL." : ".PARTITIONING.";
  return add(
    `IFCWALL('${guid()}',$,'${escapeStep(wall.id)}',$,$,${wallPlacement},${productShape},$,${predefined})`,
  );
}

/** Emit a single IfcSlab covering the storey footprint. Returns its ref. */
function emitSlab(
  graph: PlanGraph,
  storeyPlacement: string,
  geomContext: string,
  guid: () => string,
  add: (body: string) => string,
): string {
  const w = Math.max(graph.bounds.width, 1);
  const h = Math.max(graph.bounds.height, 1);
  // DECISION: no slab thickness in the kernel; use a conventional 150 mm slab.
  const thicknessMm = 150;

  const slabOrigin = add("IFCCARTESIANPOINT((0.,0.,0.))");
  const slabAxisZ = add("IFCDIRECTION((0.,0.,1.))");
  const slabAxisX = add("IFCDIRECTION((1.,0.,0.))");
  const slabPlacement3d = add(
    `IFCAXIS2PLACEMENT3D(${slabOrigin},${slabAxisZ},${slabAxisX})`,
  );
  const slabPlacement = add(
    `IFCLOCALPLACEMENT(${storeyPlacement},${slabPlacement3d})`,
  );

  const profileOrigin = add(
    `IFCCARTESIANPOINT((${num(w / 2)},${num(h / 2)}))`,
  );
  const profileAxisX = add("IFCDIRECTION((1.,0.))");
  const profilePlacement = add(
    `IFCAXIS2PLACEMENT2D(${profileOrigin},${profileAxisX})`,
  );
  const profile = add(
    `IFCRECTANGLEPROFILEDEF(.AREA.,$,${profilePlacement},${num(w)},${num(h)})`,
  );

  const extrudeOrigin = add("IFCCARTESIANPOINT((0.,0.,0.))");
  const extrudeAxisZ = add("IFCDIRECTION((0.,0.,1.))");
  const extrudeAxisX = add("IFCDIRECTION((1.,0.,0.))");
  const extrudePlacement = add(
    `IFCAXIS2PLACEMENT3D(${extrudeOrigin},${extrudeAxisZ},${extrudeAxisX})`,
  );
  // Slab is extruded downward so its top face sits at storey level 0.
  const extrudeDir = add("IFCDIRECTION((0.,0.,-1.))");
  const solid = add(
    `IFCEXTRUDEDAREASOLID(${profile},${extrudePlacement},${extrudeDir},${num(thicknessMm)})`,
  );
  const shapeRep = add(
    `IFCSHAPEREPRESENTATION(${geomContext},'Body','SweptSolid',(${solid}))`,
  );
  const productShape = add(
    `IFCPRODUCTDEFINITIONSHAPE($,$,(${shapeRep}))`,
  );

  return add(
    `IFCSLAB('${guid()}',$,'Floor Slab',$,$,${slabPlacement},${productShape},$,.FLOOR.)`,
  );
}

/** Wrap entity instance lines in the ISO-10303-21 file envelope. */
function assembleStepFile(lines: string[]): string {
  const header = [
    "ISO-10303-21;",
    "HEADER;",
    "FILE_DESCRIPTION(('ViewDefinition [CoordinationView]'),'2;1');",
    "FILE_NAME('atelier-export.ifc','2026-05-16T00:00:00',(''),(''),'Atelier v2 IFC4 writer','Atelier','');",
    "FILE_SCHEMA(('IFC4'));",
    "ENDSEC;",
    "DATA;",
  ];
  const footer = ["ENDSEC;", "END-ISO-10303-21;"];
  return [...header, ...lines, ...footer].join("\n") + "\n";
}

/** Format a number as a STEP REAL literal (always contains a decimal point). */
function num(value: number): string {
  if (!Number.isFinite(value)) return "0.";
  const r = Math.round(value * 1e6) / 1e6;
  return Number.isInteger(r) ? `${r}.` : `${r}`;
}

/** Escape a string for a STEP single-quoted string literal. */
function escapeStep(value: string): string {
  return value.replace(/'/g, "''");
}

/**
 * Generate a compliant 22-character IfcGloballyUniqueId. IFC uses a custom
 * base-64 encoding of a 128-bit value; a deterministic counter-derived value
 * is sufficient for a structurally valid file.
 */
const IFC_B64 =
  "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_$";
let guidCounter = 0;
function pseudoGuid(): string {
  // Spread a monotonically increasing counter across 128 bits of entropy.
  const n = ++guidCounter;
  const bytes = new Array<number>(16);
  for (let i = 0; i < 16; i++) {
    bytes[i] = (n * 2654435761 + i * 40503) & 0xff;
  }
  // Encode 16 bytes as 22 base-64 characters (first char uses 2 bits).
  let out = "";
  let acc = 0;
  let bits = 0;
  const chunks: number[] = [];
  for (const b of bytes) {
    acc = (acc << 8) | b;
    bits += 8;
    while (bits >= 6) {
      bits -= 6;
      chunks.push((acc >> bits) & 0x3f);
    }
  }
  if (bits > 0) {
    chunks.push((acc << (6 - bits)) & 0x3f);
  }
  for (const c of chunks.slice(0, 22)) {
    out += IFC_B64[c];
  }
  return out.padEnd(22, "0");
}
