/**
 * Print-ready PDF export for the packaging stage.
 *
 * Produces a genuine, openable single-page PDF of the dimensioned plan/layout
 * for both `home` and `hardscape` projects. The approach is deliberately
 * keyless and fully client-side:
 *
 *  1. take the plan SVG already rendered on the page (the *actual* drawn
 *     sheet — same source the SVG export uses);
 *  2. rasterize it to a high-DPI PNG via an offscreen `<canvas>`;
 *  3. embed that PNG into a jsPDF landscape sheet, under a small title block.
 *
 * `jspdf` is already a project dependency (used nowhere else yet), so no new
 * package is needed. Rasterize-then-embed is chosen over vector SVG-in-PDF
 * because it needs no `svg2pdf.js` plugin and renders identically to what the
 * user sees on screen — fonts, fills and all.
 */
import { jsPDF } from "jspdf";

/** Sheet metadata drawn into the PDF's title block. */
export interface PlanPdfMeta {
  /** Headline sheet title, e.g. "Dimensioned Floor Plan". */
  title: string;
  /** One-line subtitle, e.g. the style or site extents. */
  subtitle: string;
}

/** Target raster resolution for the embedded plan image, in CSS pixels. */
const RASTER_WIDTH = 2200;

/**
 * Rasterize an `<svg>` element to a PNG data URL at a fixed pixel width,
 * preserving the SVG's aspect ratio. Resolves to `null` if the browser blocks
 * the draw (e.g. a tainted canvas) so callers can degrade gracefully.
 */
async function svgToPngDataUrl(
  svg: SVGSVGElement,
): Promise<{ url: string; width: number; height: number } | null> {
  // Clone so the inlined namespace / explicit size never touch the live SVG.
  const clone = svg.cloneNode(true) as SVGSVGElement;
  clone.setAttribute("xmlns", "http://www.w3.org/2000/svg");

  // Derive an aspect ratio from the viewBox, falling back to the rendered box.
  const vb = svg.viewBox.baseVal;
  const rect = svg.getBoundingClientRect();
  const aspect =
    vb && vb.width > 0 && vb.height > 0
      ? vb.height / vb.width
      : rect.width > 0
        ? rect.height / rect.width
        : 0.75;

  const width = RASTER_WIDTH;
  const height = Math.round(width * aspect);
  clone.setAttribute("width", String(width));
  clone.setAttribute("height", String(height));

  const serialized = new XMLSerializer().serializeToString(clone);
  const svgBlob = new Blob(
    ['<?xml version="1.0" encoding="UTF-8"?>\n', serialized],
    { type: "image/svg+xml;charset=utf-8" },
  );
  const svgUrl = URL.createObjectURL(svgBlob);

  try {
    const image = await loadImage(svgUrl);
    const canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    const ctx = canvas.getContext("2d");
    if (!ctx) return null;
    // Paint the dark sheet backdrop so the PNG is not transparent.
    ctx.fillStyle = "#100e0b";
    ctx.fillRect(0, 0, width, height);
    ctx.drawImage(image, 0, 0, width, height);
    return { url: canvas.toDataURL("image/png"), width, height };
  } catch {
    return null;
  } finally {
    URL.revokeObjectURL(svgUrl);
  }
}

/** Promise-wrap `<img>` loading from a URL. */
function loadImage(url: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error("svg raster failed"));
    img.src = url;
  });
}

/**
 * Build a print-ready PDF from a plan SVG element. Returns the PDF as a
 * `Blob`, or `null` when rasterization is blocked by the browser.
 *
 * The sheet is US Letter landscape (11 × 8.5 in) with a title block at the
 * top and the plan image fitted into the remaining area, centered.
 */
export async function exportPlanPdf(
  svg: SVGSVGElement,
  meta: PlanPdfMeta,
): Promise<Blob | null> {
  const raster = await svgToPngDataUrl(svg);
  if (!raster) return null;

  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "letter" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 36; // 0.5 in

  // --- Title block --------------------------------------------------------
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.setTextColor(20, 18, 14);
  doc.text(meta.title, margin, margin + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(110, 104, 92);
  doc.text(meta.subtitle, margin, margin + 26);

  doc.setFontSize(9);
  doc.text("Generated by Atelier", pageW - margin, margin + 8, {
    align: "right",
  });
  doc.text(
    new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    pageW - margin,
    margin + 22,
    { align: "right" },
  );

  // A hairline rule under the title block.
  doc.setDrawColor(210, 138, 85);
  doc.setLineWidth(1);
  const ruleY = margin + 38;
  doc.line(margin, ruleY, pageW - margin, ruleY);

  // --- Plan image ---------------------------------------------------------
  const availW = pageW - margin * 2;
  const availH = pageH - ruleY - margin - 12;
  const imgAspect = raster.height / raster.width;
  let drawW = availW;
  let drawH = drawW * imgAspect;
  if (drawH > availH) {
    drawH = availH;
    drawW = drawH / imgAspect;
  }
  const drawX = (pageW - drawW) / 2;
  const drawY = ruleY + 12 + (availH - drawH) / 2;
  doc.addImage(raster.url, "PNG", drawX, drawY, drawW, drawH);

  return doc.output("blob");
}
