CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, email TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS briefs (id TEXT PRIMARY KEY, user_id TEXT, data JSON, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS stamp_applicants (id TEXT PRIMARY KEY, name TEXT, email TEXT, state TEXT, license_num TEXT, status TEXT DEFAULT 'pending', created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS outreach_events (id TEXT PRIMARY KEY, email TEXT, persona TEXT, day INTEGER, sent_at DATETIME DEFAULT CURRENT_TIMESTAMP);